In [1]:
import math

In [2]:
type(math)

module

In [3]:
num1 = 5.99

In [4]:
math.ceil(num1)

6

In [5]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [6]:
math.pi

3.141592653589793

In [7]:
math.log(10323)

9.24212969446559

In [9]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [10]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [11]:
import math as mt

In [12]:
mt.pi

3.141592653589793

In [13]:
import math

In [14]:
m = math

In [15]:
m.pi

3.141592653589793

In [16]:
from math import *

In [17]:
log(12324)

9.419303859716559

In [18]:
pi

3.141592653589793

In [19]:
from math import *
from numpy import *

In [20]:
pi

3.141592653589793

In [21]:
log(32,2)

TypeError: return arrays must be of ArrayType

In [22]:
from math import log, pi
from numpy import asarray

In [24]:
type(numpy)

module

In [25]:
type(numpy.random)

module

In [23]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [26]:
dir(numpy.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

In [27]:
rolls  = numpy.random.randint(low = 1, high = 6, size = 10)

In [28]:
rolls

array([4, 1, 1, 3, 4, 3, 5, 4, 4, 2])

In [29]:
type(rolls)

numpy.ndarray

In [30]:
dir(rolls)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [31]:
rolls.cumsum()

array([ 4,  5,  6,  9, 13, 16, 21, 25, 29, 31])

In [32]:
rolls.mean()

3.1

In [33]:
rolls.std()

1.3

In [34]:
rolls.min()

1

In [35]:
rolls.max()

5

In [37]:
[3, 4, 1, 2, 2, 1] + 10

TypeError: can only concatenate list (not "int") to list

In [38]:
type(rolls)

numpy.ndarray

In [40]:
rolls

array([4, 1, 1, 3, 4, 3, 5, 4, 4, 2])

In [39]:
rolls + 10

array([14, 11, 11, 13, 14, 13, 15, 14, 14, 12])

In [41]:
rolls - 10

array([-6, -9, -9, -7, -6, -7, -5, -6, -6, -8])

In [42]:
rolls * 10

array([40, 10, 10, 30, 40, 30, 50, 40, 40, 20])

In [43]:
rolls <= 3

array([False,  True,  True,  True, False,  True, False, False, False,
        True])

In [44]:
[4, 1, 1, 3, 4, 3, 5, 4, 4, 2]

[4, 1, 1, 3, 4, 3, 5, 4, 4, 2]

In [45]:
xlist = [[1,2,3],[2,4,6]]

In [46]:
x = numpy.asarray(xlist)

In [51]:
type(x)

numpy.ndarray

In [47]:
x.shape

(2, 3)

In [48]:
x

array([[1, 2, 3],
       [2, 4, 6]])

In [49]:
x[1, -1]

6

In [50]:
xlist[1,-1]

TypeError: list indices must be integers or slices, not tuple

In [52]:
import tensorflow as tf

In [53]:
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)

In [54]:
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>